services:
  - type: web
    name: meatlovers-api
    env: node
    rootDir: api
    plan: free
    buildCommand: npm install && npm run build
    startCommand: cd api && npm run start:prod
    autoDeploy: true
