"use client";

import { useEffect, useState } from "react";
import { AttendanceSummary, getAttendanceSummary, readable } from "@/lib/hr";

const today = new Date().toISOString().slice(0, 10);

export function AttendanceReports() {
  const [date, setDate] = useState(today); const [summary, setSummary] = useState<AttendanceSummary | null>(null); const [error, setError] = useState("");
  useEffect(() => { getAttendanceSummary(date).then(setSummary).catch((err) => setError(err instanceof Error ? err.message : "Unable to load attendance report.")); }, [date]);
  const cards = [["Total active staff", summary?.totalStaff ?? "—"], ["Marked attendance", summary?.markedAttendance ?? "—"], ["Unmarked staff", summary?.unmarked ?? "—"], ["Attendance rate", summary ? `${summary.totalStaff ? Math.round((summary.markedAttendance / summary.totalStaff) * 100) : 0}%` : "—"]];
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-sm font-semibold text-blue-700">Attendance management</p><h1 className="mt-1 text-3xl font-black text-zinc-950">Attendance reports</h1><p className="mt-2 text-sm text-zinc-600">Daily attendance summary and status breakdown.</p><div className="mt-6 flex max-w-xs"><label className="w-full text-sm font-semibold text-zinc-700">Report date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="mt-1 w-full rounded-md border border-zinc-300 px-3 py-2 outline-none focus:border-blue-600" /></label></div>{error && <div className="mt-5 rounded-md border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{error}</div>}<section className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{cards.map(([label, value]) => <div key={label as string} className="rounded-xl border border-zinc-200 bg-white p-5 shadow-sm"><p className="text-sm text-zinc-600">{label}</p><p className="mt-2 text-3xl font-black text-zinc-950">{value}</p></div>)}</section><section className="mt-6 max-w-2xl rounded-xl border border-zinc-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black text-zinc-950">Status breakdown</h2><div className="mt-5 space-y-4">{summary?.breakdown?.length ? summary.breakdown.map((item) => <div key={item.status} className="flex items-center justify-between border-b border-zinc-100 pb-3 last:border-0"><span className="font-medium text-zinc-700">{readable(item.status)}</span><span className="rounded-full bg-blue-50 px-3 py-1 text-sm font-bold text-blue-700">{item.count}</span></div>) : <p className="text-sm text-zinc-500">No attendance has been marked for this date.</p>}</div></section></main>;
}
