"use client";

import { useEffect, useMemo, useState } from "react";
import { AttendanceRecord, getAttendance } from "@/lib/hr";

const today = new Date().toISOString().slice(0, 10);
export function WorkHoursCalculation() {
  const [date, setDate] = useState(today); const [records, setRecords] = useState<AttendanceRecord[]>([]); const [error, setError] = useState("");
  useEffect(() => { getAttendance(date).then(setRecords).catch((err) => setError(err instanceof Error ? err.message : "Unable to load work hours.")); }, [date]);
  const totalHours = useMemo(() => records.reduce((total, item) => total + Number(item.hours_worked || 0), 0), [records]);
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8"><p className="text-sm font-semibold text-blue-700">Attendance management</p><h1 className="mt-1 text-3xl font-black text-zinc-950">Work hours calculation</h1><p className="mt-2 text-sm text-zinc-600">Review daily recorded hours. Hours are supplied from attendance records for payroll and scheduling.</p><div className="mt-6 flex max-w-xs"><label className="w-full text-sm font-semibold text-zinc-700">Work date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="mt-1 w-full rounded-md border border-zinc-300 px-3 py-2 outline-none focus:border-blue-600" /></label></div>{error && <div className="mt-5 rounded-md border border-blue-200 bg-blue-50 p-3 text-sm text-blue-800">{error}</div>}<section className="mt-6 rounded-xl border border-zinc-200 bg-white p-5 shadow-sm"><p className="text-sm text-zinc-600">Total recorded work hours</p><p className="mt-2 text-4xl font-black text-blue-700">{totalHours.toFixed(2)} hrs</p></section><section className="mt-6 overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="bg-zinc-50 text-xs uppercase text-zinc-500"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Recorded hours</th></tr></thead><tbody className="divide-y divide-zinc-100">{records.length ? records.map((record) => <tr key={String(record.id)}><td className="px-5 py-4 font-bold text-zinc-900">{record.user.full_name}</td><td className="px-5 py-4 text-zinc-700">{record.status.replaceAll("_", " ")}</td><td className="px-5 py-4 font-bold text-blue-700">{Number(record.hours_worked || 0).toFixed(2)} hrs</td></tr>) : <tr><td colSpan={3} className="px-5 py-10 text-center text-zinc-500">No work hours have been recorded for this date.</td></tr>}</tbody></table></section></main>;
}
