<?php
declare(strict_types=1);

use Support\Router;
use Controllers\ApprovalsController;
use Controllers\AssetsController;
use Controllers\AuthController;
use Controllers\BarController;
use Controllers\CustomersController;
use Controllers\DispatchController;
use Controllers\EnforcementController;
use Controllers\FinanceController;
use Controllers\HRMController;
use Controllers\IncomeStatementController;
use Controllers\InventoryController;
use Controllers\KitchenController;
use Controllers\MonitoringController;
use Controllers\OrdersController;
use Controllers\PaymentsController;
use Controllers\ProductsController;
use Controllers\ReportsController;
use Controllers\StaffPerformanceController;
use Controllers\SuppliersController;
use Controllers\UnsoldFoodController;
use Controllers\WebsiteController;

$router = new Router();
$router->post('/api/auth/login', [AuthController::class, 'login']);
$router->get('/api/products', [ProductsController::class, 'index']);
$router->post('/api/products', [ProductsController::class, 'store']);
$router->get('/api/suppliers', [SuppliersController::class, 'index']);
$router->post('/api/suppliers', [SuppliersController::class, 'store']);
$router->get('/api/customers', [CustomersController::class, 'index']);
$router->post('/api/customers', [CustomersController::class, 'store']);
$router->get('/api/inventory/stock-summary', [InventoryController::class, 'stockSummary']);
$router->post('/api/inventory/stock-in', [InventoryController::class, 'stockIn']);
$router->get('/api/orders', [OrdersController::class, 'index']);
$router->post('/api/orders', [OrdersController::class, 'store']);
$router->post('/api/payments/cash-settle/{id}', [PaymentsController::class, 'cashSettle']);
$router->get('/api/reports/daily', [ReportsController::class, 'daily']);
$router->get('/api/monitoring/overview', [MonitoringController::class, 'overview']);
$router->post('/api/kitchen/orders/{id}/mark-preparing', [KitchenController::class, 'markPreparing']);
$router->post('/api/payments/mpesa-pending/{id}', [PaymentsController::class, 'mpesaPending']);
$router->get('/api/payments/receipt/{id}', [PaymentsController::class, 'receipt']);
$router->get('/api/payments/print-queue', [PaymentsController::class, 'printQueue']);
$router->get('/api/payments/audit', [PaymentsController::class, 'audit']);
$router->get('/api/monitoring/live-control', [MonitoringController::class, 'liveControl']);
$router->get('/api/monitoring/low-stock-alerts', [MonitoringController::class, 'lowStockAlerts']);
$router->get('/api/monitoring/pending-approvals', [MonitoringController::class, 'pendingApprovals']);
$router->get('/api/monitoring/pending-mpesa', [MonitoringController::class, 'pendingMpesa']);
$router->get('/api/monitoring/unsold-food-alerts', [MonitoringController::class, 'unsoldFoodAlerts']);
$router->get('/api/approvals/history', [ApprovalsController::class, 'history']);
$router->post('/api/approvals/{id}/apply', [ApprovalsController::class, 'apply']);
$router->get('/api/finance/categories', [FinanceController::class, 'categories']);
$router->post('/api/finance/categories', [FinanceController::class, 'storeCategory']);
$router->get('/api/finance/profitability-split', [FinanceController::class, 'profitabilitySplit']);
$router->post('/api/finance/reconciliations', [FinanceController::class, 'storeReconciliation']);
$router->get('/api/finance/reconciliations', [FinanceController::class, 'reconciliations']);
$router->get('/api/finance/variance-alerts', [FinanceController::class, 'varianceAlerts']);
$router->post('/api/income-statement/snapshot/daily', [IncomeStatementController::class, 'snapshotDaily']);
$router->post('/api/income-statement/snapshot/weekly', [IncomeStatementController::class, 'snapshotWeekly']);
$router->post('/api/income-statement/snapshot/monthly', [IncomeStatementController::class, 'snapshotMonthly']);
$router->post('/api/income-statement/snapshot/annual', [IncomeStatementController::class, 'snapshotAnnual']);
$router->get('/api/income-statement/snapshots', [IncomeStatementController::class, 'snapshots']);
$router->get('/api/staff-motivation/leaderboard', [StaffPerformanceController::class, 'leaderboard']);
$router->get('/api/staff-motivation/service-performance', [StaffPerformanceController::class, 'servicePerformance']);
$router->post('/api/staff-motivation/customer-rating', [StaffPerformanceController::class, 'storeCustomerRating']);
$router->get('/api/staff-motivation/bonus-rules', [StaffPerformanceController::class, 'bonusRules']);
$router->post('/api/staff-motivation/bonus-rules', [StaffPerformanceController::class, 'storeBonusRule']);
$router->get('/api/staff-motivation/daily-targets', [StaffPerformanceController::class, 'dailyTargets']);
$router->post('/api/staff-motivation/daily-targets', [StaffPerformanceController::class, 'storeDailyTarget']);
$router->get('/api/staff-motivation/dashboard', [StaffPerformanceController::class, 'motivationDashboard']);
$router->get('/api/staff-motivation/hrm-report', [StaffPerformanceController::class, 'hrmReport']);
$router->get('/api/deliveries', [DispatchController::class, 'orders']);
$router->post('/api/deliveries', [DispatchController::class, 'createDeliveryOrder']);
$router->get('/api/riders', [DispatchController::class, 'riders']);
$router->post('/api/riders', [DispatchController::class, 'storeRider']);
$router->post('/api/dispatch/orders/{id}/assign-rider', [DispatchController::class, 'assignRider']);
$router->post('/api/dispatch/orders/{id}/fail', [DispatchController::class, 'failDelivery']);
$router->get('/api/dispatch/performance-report', [DispatchController::class, 'performanceReport']);
$router->get('/api/storekeeping/supplier-invoices', [InventoryController::class, 'supplierInvoices']);
$router->post('/api/storekeeping/supplier-invoices', [InventoryController::class, 'createSupplierInvoice']);
$router->post('/api/storekeeping/supplier-invoices/{id}/approve', [InventoryController::class, 'approveSupplierInvoice']);
$router->post('/api/storekeeping/supplier-invoices/{id}/reject', [InventoryController::class, 'rejectSupplierInvoice']);
$router->get('/api/storekeeping/receiving-notes', [InventoryController::class, 'receivingNotes']);
$router->post('/api/storekeeping/receiving-notes', [InventoryController::class, 'createReceivingNote']);
$router->post('/api/storekeeping/receiving-notes/{id}/receive', [InventoryController::class, 'receiveStock']);
$router->get('/api/storekeeping/stock-transfers', [InventoryController::class, 'stockTransfers']);
$router->post('/api/storekeeping/stock-transfers', [InventoryController::class, 'createStockTransfer']);
$router->post('/api/storekeeping/stock-transfers/{id}/approve', [InventoryController::class, 'approveStockTransfer']);
$router->get('/api/storekeeping/stock-movement-report', [InventoryController::class, 'stockMovementReport']);
$router->get('/api/storekeeping/supplier-performance-report', [InventoryController::class, 'supplierPerformanceReport']);
$router->get('/api/production/recipes', [KitchenController::class, 'recipes']);
$router->post('/api/production/recipes', [KitchenController::class, 'createRecipe']);
$router->get('/api/production/plans', [KitchenController::class, 'productionPlans']);
$router->post('/api/production/plans', [KitchenController::class, 'createProductionPlan']);
$router->post('/api/production/plans/{id}/start', [KitchenController::class, 'startProductionPlan']);
$router->post('/api/production/plans/{id}/complete', [KitchenController::class, 'completeProductionPlan']);
$router->post('/api/production/ingredient-consumption', [KitchenController::class, 'recordIngredientConsumption']);
$router->post('/api/production/wastage', [KitchenController::class, 'recordWastage']);
$router->get('/api/production/menu-engineering-report', [KitchenController::class, 'menuEngineeringReport']);
$router->get('/api/production/food-cost-report', [KitchenController::class, 'foodCostReport']);
$router->get('/api/pricing/rules', [ProductsController::class, 'pricingRules']);
$router->post('/api/pricing/rules', [ProductsController::class, 'createPricingRule']);
$router->get('/api/pricing/category-dashboard/{id}', [ProductsController::class, 'categoryDashboard']);
$router->post('/api/products/{id}/update-price', [ProductsController::class, 'updatePrice']);
$router->post('/api/products/{id}/deactivate', [ProductsController::class, 'deactivateProduct']);
$router->post('/api/products/{id}/activate', [ProductsController::class, 'activateProduct']);
$router->get('/api/products/price-change-audit', [ProductsController::class, 'priceChangeAudit']);
$router->get('/api/products/margin-alerts', [ProductsController::class, 'marginAlerts']);
$router->post('/api/products/margin-alerts/generate', [ProductsController::class, 'generateMarginAlerts']);
$router->get('/api/crm/customer-segments', [CustomersController::class, 'customerSegments']);
$router->get('/api/crm/visit-history', [CustomersController::class, 'visitHistory']);
$router->post('/api/crm/visit-history', [CustomersController::class, 'recordVisit']);
$router->get('/api/crm/loyalty-transactions', [CustomersController::class, 'loyaltyTransactions']);
$router->post('/api/crm/loyalty-transactions', [CustomersController::class, 'recordLoyaltyTransaction']);
$router->get('/api/crm/follow-ups', [CustomersController::class, 'followUps']);
$router->post('/api/crm/follow-ups', [CustomersController::class, 'createFollowUp']);
$router->post('/api/crm/follow-ups/{id}/status', [CustomersController::class, 'updateFollowUpStatus']);
$router->post('/api/crm/generate-abandoned-lead-followups', [CustomersController::class, ' generateAbandonedLeadFollowUps']);
$router->post('/api/crm/generate-reminder-placeholders', [CustomersController::class, 'generateReminderPlaceholders']);
$router->get('/api/crm/repeat-customer-dashboard', [CustomersController::class, 'repeatCustomerDashboard']);
$router->get('/api/assets/assignments', [AssetsController::class, 'assignments']);
$router->post('/api/assets/assignments', [AssetsController::class, 'createAssignment']);
$router->get('/api/assets/maintenance-schedules', [AssetsController::class, 'maintenanceSchedules']);
$router->post('/api/assets/maintenance-schedules', [AssetsController::class, 'createMaintenanceSchedule']);
$router->post('/api/assets/maintenance-schedules/{id}/complete', [AssetsController::class, 'completeMaintenanceSchedule']);
$router->get('/api/assets/repair-logs', [AssetsController::class, 'repairLogs']);
$router->post('/api/assets/repair-logs', [AssetsController::class, 'createRepairLog']);
$router->get('/api/assets/damage-reports', [AssetsController::class, 'damageReports']);
$router->post('/api/assets/damage-reports', [AssetsController::class, 'createDamageReport']);
$router->get('/api/assets/writeoff-requests', [AssetsController::class, 'writeoffRequests']);
$router->post('/api/assets/writeoff-requests', [AssetsController::class, 'createWriteoffRequest']);
$router->post('/api/assets/writeoff-requests/{id}/approve', [AssetsController::class, 'approveWriteoffRequest']);
$router->post('/api/assets/writeoff-requests/{id}/apply', [AssetsController::class, 'applyWriteoffRequest']);
$router->get('/api/assets/lifecycle-dashboard', [AssetsController::class, 'lifecycleDashboard']);
$router->get('/api/hrm/shifts', [HRMController::class, 'shifts']);
$router->post('/api/hrm/shifts', [HRMController::class, 'createShift']);
$router->get('/api/hrm/duty-rosters', [HRMController::class, 'dutyRosters']);
$router->post('/api/hrm/duty-rosters', [HRMController::class, 'createDutyRoster']);
$router->get('/api/hrm/attendance', [HRMController::class, 'attendance']);
$router->post('/api/hrm/attendance/clock-in', [HRMController::class, 'clockIn']);
$router->post('/api/hrm/attendance/clock-out', [HRMController::class, 'clockOut']);
$router->get('/api/hrm/absences', [HRMController::class, 'absences']);
$router->post('/api/hrm/absences', [HRMController::class, 'createAbsence']);
$router->get('/api/hrm/payroll-placeholders', [HRMController::class, 'payrollPlaceholders']);
$router->post('/api/hrm/payroll-placeholders', [HRMController::class, 'createPayrollPlaceholder']);
$router->get('/api/hrm/compliance-dashboard', [HRMController::class, 'complianceDashboard']);
$router->get('/api/enforcement/staff-incidents', [EnforcementController::class, 'staffIncidents']);
$router->post('/api/enforcement/staff-incidents', [EnforcementController::class, 'createStaffIncident']);
$router->get('/api/enforcement/risk-scores', [EnforcementController::class, 'riskScores']);
$router->post('/api/enforcement/generate-risk-scores', [EnforcementController::class, 'generateRiskScores']);
$router->get('/api/enforcement/actions', [EnforcementController::class, 'actions']);
$router->post('/api/enforcement/actions', [EnforcementController::class, 'createAction']);
$router->get('/api/enforcement/dashboard', [EnforcementController::class, 'dashboard']);
$router->get('/api/enforcement/audit-feed', [EnforcementController::class, 'auditFeed']);
$router->get('/api/approvals', [ApprovalsController::class, 'index']);
$router->post('/api/approvals/{id}/approve', [ApprovalsController::class, 'approve']);
$router->post('/api/approvals/{id}/reject', [ApprovalsController::class, 'reject']);
$router->post('/api/orders/{id}/request-cancellation', [OrdersController::class, 'requestCancellation']);
$router->post('/api/orders/{id}/request-discount', [OrdersController::class, 'requestDiscount']);
$router->post('/api/inventory/request-stock-adjustment', [InventoryController::class, 'requestStockAdjustment']);
$router->get('/api/bar/stock', [BarController::class, 'stock']);
$router->post('/api/bar/stock-issue', [BarController::class, 'stockIssue']);
$router->get('/api/kitchen/orders', [KitchenController::class, 'orders']);
$router->post('/api/kitchen/orders/{id}/mark-ready', [KitchenController::class, 'markReady']);
$router->get('/api/dispatch/orders', [DispatchController::class, 'orders']);
$router->post('/api/dispatch/orders/{id}/dispatch', [DispatchController::class, 'dispatch']);
$router->post('/api/dispatch/orders/{id}/deliver', [DispatchController::class, 'deliver']);
$router->get('/api/unsold-food', [UnsoldFoodController::class, 'index']);
$router->post('/api/unsold-food', [UnsoldFoodController::class, 'store']);
$router->get('/api/assets', [AssetsController::class, 'index']);
$router->post('/api/assets', [AssetsController::class, 'store']);
$router->get('/api/hrm/staff', [HRMController::class, 'staff']);
$router->post('/api/hrm/staff', [HRMController::class, 'storeStaff']);
$router->get('/api/staff-performance', [StaffPerformanceController::class, 'index']);
$router->post('/api/staff-performance', [StaffPerformanceController::class, 'store']);
$router->get('/api/finance/transactions', [FinanceController::class, 'index']);
$router->post('/api/finance/transactions', [FinanceController::class, 'store']);
$router->get('/api/income-statement/daily', [IncomeStatementController::class, 'daily']);
$router->get('/api/income-statement/weekly', [IncomeStatementController::class, 'weekly']);
$router->get('/api/income-statement/monthly', [IncomeStatementController::class, 'monthly']);
$router->get('/api/income-statement/annual', [IncomeStatementController::class, 'annual']);
$router->post('/api/website/leads', [WebsiteController::class, 'storeLead']);
$router->post('/api/website/catering-enquiries', [WebsiteController::class, 'storeCateringEnquiry']);
$router->post('/api/website/delivery-enquiries', [WebsiteController::class, 'storeDeliveryEnquiry']);
$router->post('/api/website/feedback', [WebsiteController::class, 'storeFeedback']);
$router->get('/api/admin/website/leads', [WebsiteController::class, 'leads']);
$router->get('/api/admin/website/catering-enquiries', [WebsiteController::class, 'cateringEnquiries']);
$router->get('/api/admin/website/delivery-enquiries', [WebsiteController::class, 'deliveryEnquiries']);
$router->get('/api/admin/website/feedback', [WebsiteController::class, 'feedback']);
$router->get('/api/admin/website/acquisition-summary', [WebsiteController::class, 'acquisitionSummary']);
$router->post('/api/admin/website/leads/{id}/status', [WebsiteController::class, 'updateLeadStatus']);
$router->post('/api/admin/website/catering-enquiries/{id}/status', [WebsiteController::class, 'updateCateringStatus']);
$router->post('/api/admin/website/delivery-enquiries/{id}/status', [WebsiteController::class, 'updateDeliveryStatus']);
$router->post('/api/admin/website/feedback/{id}/status', [WebsiteController::class, 'updateFeedbackStatus']);

return $router;
