CREATE TABLE users (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
full_name VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE,
phone VARCHAR(50) UNIQUE,
password_hash TEXT NOT NULL,
role ENUM(
'SUPER_ADMIN',
'ADMIN',
'MANAGER',
'CASHIER',
'WAITER',
'CHEF',
'STOREKEEPER',
'BARMAN',
'DISPATCHER',
'ACCOUNTANT',
'HR'
) NOT NULL,
is_active BOOLEAN DEFAULT TRUE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
