CREATE TABLE customers (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
full_name VARCHAR(255) NOT NULL,
phone VARCHAR(50),
email VARCHAR(255),
customer_type ENUM(
'WALK_IN',
'REGULAR',
'VIP',
'CORPORATE',
'DELIVERY'



) DEFAULT 'WALK_IN',
loyalty_points DECIMAL(12,2) DEFAULT 0,
notes TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
