CREATE TABLE suppliers (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
supplier_name VARCHAR(255) NOT NULL,
contact_person VARCHAR(255),
phone VARCHAR(50),
email VARCHAR(255),
physical_address TEXT,
supplier_type ENUM(
'FOOD',
'SOFT_DRINKS',
'ALCOHOL',
'GENERAL'
) NOT NULL,
status ENUM(
'ACTIVE',
'SUSPENDED'
) DEFAULT 'ACTIVE',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
