CREATE TABLE products (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
product_name VARCHAR(255) NOT NULL,
product_category ENUM(
'FOOD',
'SOFT_DRINK',
'ALCOHOLIC_DRINK'
) NOT NULL,
selling_price DECIMAL(12,2) NOT NULL,
cost_price DECIMAL(12,2) NOT NULL,
barcode VARCHAR(255),
is_active BOOLEAN DEFAULT TRUE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
