CREATE TABLE stock_items (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
product_id BIGINT NOT NULL,


current_quantity DECIMAL(12,2) DEFAULT 0,
reorder_level DECIMAL(12,2) DEFAULT 0,
FOREIGN KEY (product_id)
REFERENCES products(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
