CREATE TABLE stock_movements (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
product_id BIGINT NOT NULL,
movement_type ENUM(
'PURCHASE',
'STORE_TO_KITCHEN',
'STORE_TO_BAR',
'BAR_SALE',
'KITCHEN_USAGE',
'WASTAGE',
'ADJUSTMENT'
) NOT NULL,
quantity DECIMAL(12,2) NOT NULL,
reference_number VARCHAR(255),
notes TEXT,
user_id BIGINT,
FOREIGN KEY (product_id)
REFERENCES products(id),
FOREIGN KEY (user_id)
REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
