CREATE TABLE orders (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
order_number VARCHAR(255) UNIQUE,
customer_id BIGINT,
waiter_id BIGINT,
table_number VARCHAR(50),
order_status ENUM(
'PENDING',
'PREPARING',
'READY',
'SERVED',
'PAID',
'CANCELLED'
) DEFAULT 'PENDING',
subtotal DECIMAL(12,2) DEFAULT 0,
discount_amount DECIMAL(12,2) DEFAULT 0,
total_amount DECIMAL(12,2) DEFAULT 0,
FOREIGN KEY (customer_id)
REFERENCES customers(id),


FOREIGN KEY (waiter_id)
REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
