CREATE TABLE payments (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
order_id BIGINT NOT NULL,
payment_method ENUM(
'CASH',
'MPESA',
'CARD'
) NOT NULL,
amount DECIMAL(12,2) NOT NULL,
transaction_reference VARCHAR(255),
payment_status ENUM(
'PENDING',
'SUCCESS',
'FAILED'
) DEFAULT 'PENDING',
FOREIGN KEY (order_id)
REFERENCES orders(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
