CREATE TABLE assets (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
asset_name VARCHAR(255) NOT NULL,
asset_category VARCHAR(255),
serial_number VARCHAR(255),


purchase_cost DECIMAL(12,2),
asset_status ENUM(
'ACTIVE',
'DAMAGED',
'DISPOSED'
) DEFAULT 'ACTIVE',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
