CREATE TABLE unsold_food (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
product_id BIGINT NOT NULL,
quantity DECIMAL(12,2) NOT NULL,
reason TEXT,
declared_by BIGINT,
FOREIGN KEY (product_id)
REFERENCES products(id),
FOREIGN KEY (declared_by)
REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
