CREATE TABLE deliveries (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
order_id BIGINT NOT NULL,
customer_id BIGINT NOT NULL,
delivery_status ENUM(
'PENDING',
'DISPATCHED',
'DELIVERED',
'FAILED'
) DEFAULT 'PENDING',
rider_name VARCHAR(255),
rider_phone VARCHAR(50),
delivery_address TEXT,
FOREIGN KEY (order_id)
REFERENCES orders(id),
FOREIGN KEY (customer_id)
REFERENCES customers(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
