CREATE TABLE staff_performance (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
staff_id BIGINT NOT NULL,
report_date DATE NOT NULL,
sales_amount DECIMAL(12,2) DEFAULT 0,
orders_served INT DEFAULT 0,
customer_rating DECIMAL(5,2) DEFAULT 0,
bonus_amount DECIMAL(12,2) DEFAULT 0,
FOREIGN KEY (staff_id)
REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
