CREATE TABLE restaurant_tables (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
table_number VARCHAR(50) UNIQUE NOT NULL,
table_name VARCHAR(255),
seating_capacity INT DEFAULT 4,
table_status ENUM(
'AVAILABLE',
'OCCUPIED',
'RESERVED',
'DISABLED'
) DEFAULT 'AVAILABLE',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
