CREATE TABLE approval_requests (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
requested_by BIGINT NOT NULL,
approval_type ENUM(
'ORDER_CANCELLATION',
'DISCOUNT',
'STOCK_ADJUSTMENT',
'REFUND'
) NOT NULL,
reference_id BIGINT,
request_reason TEXT,
request_data JSON,
approval_status ENUM(
'PENDING',
'APPROVED',
'REJECTED'
) DEFAULT 'PENDING',
approved_by BIGINT,
approval_notes TEXT,
approved_at TIMESTAMP NULL,
FOREIGN KEY (requested_by)
REFERENCES users(id),
FOREIGN KEY (approved_by)
REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
