CREATE TABLE website_leads (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
full_name VARCHAR(255) NOT NULL,
phone VARCHAR(50) NOT NULL,
email VARCHAR(255),
interest_type ENUM(
'GENERAL',
'AI_ORDER_ASSISTANT',
'FOOD_ORDER',
'SOFT_DRINKS',
'ALCOHOLIC_DRINKS',
'OFFERS',
'CATERING',
'DELIVERY',
'FEEDBACK'
) DEFAULT 'GENERAL',
message TEXT,
lead_status ENUM(
'NEW',
'CONTACTED',
'CONVERTED',
'CLOSED'
) DEFAULT 'NEW',
source VARCHAR(255) DEFAULT 'WEBSITE',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
