CREATE TABLE catering_enquiries (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
lead_id BIGINT,
full_name VARCHAR(255) NOT NULL,
phone VARCHAR(50) NOT NULL,
event_date DATE,
guest_count INT,
location TEXT,
message TEXT,
enquiry_status ENUM(
'NEW',
'CONTACTED',
'QUOTED',
'CONFIRMED',
'CLOSED'
) DEFAULT 'NEW',
FOREIGN KEY (lead_id)



REFERENCES website_leads(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
