CREATE TABLE delivery_enquiries (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
lead_id BIGINT,
full_name VARCHAR(255) NOT NULL,
phone VARCHAR(50) NOT NULL,
delivery_address TEXT NOT NULL,
order_request TEXT NOT NULL,
enquiry_status ENUM(
'NEW',
'CONTACTED',
'CONFIRMED',
'DISPATCHED',
'CLOSED'
) DEFAULT 'NEW',
FOREIGN KEY (lead_id)
REFERENCES website_leads(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
