CREATE TABLE customer_feedback (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
lead_id BIGINT,
full_name VARCHAR(255),
phone VARCHAR(50),
rating INT NOT NULL,
message TEXT,
feedback_status ENUM(
'NEW',
'REVIEWED',
'ACTION_TAKEN',
'CLOSED'
) DEFAULT 'NEW',
FOREIGN KEY (lead_id)
REFERENCES website_leads(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
