CREATE TABLE print_queue (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
order_id BIGINT NOT NULL,
print_type ENUM(
'KITCHEN',
'BAR',
'CUSTOMER_RECEIPT'
) NOT NULL,
print_status ENUM(
'PENDING',
'PRINTED',
'FAILED'
) DEFAULT 'PENDING',
printed_at TIMESTAMP NULL,
FOREIGN KEY (order_id)
REFERENCES orders(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
