CREATE TABLE finance_categories (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
category_name VARCHAR(255) NOT NULL,
category_type ENUM(
'INCOME',
'EXPENSE'
) NOT NULL,
description TEXT,
is_active BOOLEAN DEFAULT TRUE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
