CREATE TABLE variance_alerts (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
variance_type ENUM(
'CASH_SHORTAGE',
'CASH_EXCESS',
'MPESA_MISMATCH',
'STOCK_VARIANCE',
'SALES_VARIANCE'
) NOT NULL,
reference_id BIGINT,
variance_amount DECIMAL(12,2) DEFAULT 0,
alert_status ENUM(
'OPEN',
'UNDER_REVIEW',
'RESOLVED',
'CLOSED'
) DEFAULT 'OPEN',
notes TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
