CREATE TABLE bonus_rules (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
rule_name VARCHAR(255) NOT NULL,
role ENUM('WAITER', 'CASHIER', 'CHEF', 'BARMAN', 'DISPATCHER') DEFAULT 'WAITER',
target_type ENUM(
'SALES_AMOUNT',
'ORDERS_SERVED',
'CUSTOMER_RATING'
) NOT NULL,
target_value DECIMAL(12,2) NOT NULL,
bonus_amount DECIMAL(12,2) NOT NULL,
is_active BOOLEAN DEFAULT TRUE,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
