CREATE TABLE customer_ratings (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
order_id BIGINT,
staff_id BIGINT NOT NULL,
rating INT NOT NULL,
comment TEXT,
rating_source ENUM(
'POS',
'WEBSITE',
'MANAGER_ENTRY'
) DEFAULT 'POS',
FOREIGN KEY (order_id) REFERENCES orders(id),
FOREIGN KEY (staff_id) REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
