CREATE TABLE daily_staff_targets (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
staff_id BIGINT NOT NULL,
target_date DATE NOT NULL,



sales_target DECIMAL(12,2) DEFAULT 0,
orders_target INT DEFAULT 0,
rating_target DECIMAL(5,2) DEFAULT 0,
target_status ENUM(
'PENDING',
'ACHIEVED',
'MISSED'
) DEFAULT 'PENDING',
FOREIGN KEY (staff_id) REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
