CREATE TABLE riders (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
rider_name VARCHAR(255) NOT NULL,
rider_phone VARCHAR(50) NOT NULL,
rider_status ENUM(
'ACTIVE',
'INACTIVE',
'SUSPENDED'
) DEFAULT 'ACTIVE',
notes TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
