CREATE TABLE supplier_invoices (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
supplier_id BIGINT NOT NULL,
invoice_number VARCHAR(255) NOT NULL,
invoice_date DATE NOT NULL,
invoice_amount DECIMAL(12,2) NOT NULL,
invoice_status ENUM(
'PENDING',
'APPROVED',
'REJECTED',
'PAID'
) DEFAULT 'PENDING',
notes TEXT,
created_by BIGINT,
FOREIGN KEY (supplier_id) REFERENCES suppliers(id),
FOREIGN KEY (created_by) REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
