CREATE TABLE stock_transfers (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
product_id BIGINT NOT NULL,
transfer_from ENUM(
'STORE',
'KITCHEN',
'BAR'
) NOT NULL,
transfer_to ENUM(
'STORE',
'KITCHEN',
'BAR'
) NOT NULL,
quantity DECIMAL(12,2) NOT NULL,
transfer_status ENUM(
'PENDING',
'APPROVED',
'REJECTED',
'COMPLETED'
) DEFAULT 'PENDING',
requested_by BIGINT NOT NULL,
approved_by BIGINT,
approved_at TIMESTAMP NULL,
notes TEXT,
FOREIGN KEY (product_id) REFERENCES products(id),
FOREIGN KEY (requested_by) REFERENCES users(id),
FOREIGN KEY (approved_by) REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
