CREATE TABLE recipes (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
menu_product_id BIGINT NOT NULL,
recipe_name VARCHAR(255) NOT NULL,
serving_size DECIMAL(12,2) DEFAULT 1,
is_active BOOLEAN DEFAULT TRUE,
FOREIGN KEY (menu_product_id) REFERENCES products(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
