CREATE TABLE pricing_rules (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
product_category ENUM(
'FOOD',
'SOFT_DRINK',
'ALCOHOLIC_DRINK'
) NOT NULL,
minimum_margin_percent DECIMAL(5,2) DEFAULT 0,
maximum_discount_percent DECIMAL(5,2) DEFAULT 0,
rule_status ENUM(
'ACTIVE',
'INACTIVE'
) DEFAULT 'ACTIVE',
notes TEXT,
created_by BIGINT,
FOREIGN KEY (created_by)
REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
