CREATE TABLE customer_visit_history (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
customer_id BIGINT NOT NULL,
order_id BIGINT,
visit_date DATE NOT NULL,
visit_source ENUM(
'WALK_IN',
'WEBSITE',
'DELIVERY',
'CATERING',
'PHONE',
'WHATSAPP'
) DEFAULT 'WALK_IN',
total_spent DECIMAL(12,2) DEFAULT 0,
FOREIGN KEY (customer_id) REFERENCES customers(id),
FOREIGN KEY (order_id) REFERENCES orders(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
