CREATE TABLE customer_follow_ups (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
customer_id BIGINT,
website_lead_id BIGINT,
feedback_id BIGINT,
follow_up_type ENUM(
'WEBSITE_LEAD',
'FEEDBACK',
'ABANDONED_LEAD',
'BIRTHDAY_REMINDER',
'ANNIVERSARY_REMINDER',
'LOYALTY_REWARD',
'MANAGER_CALL'
) NOT NULL,
follow_up_status ENUM(
'PENDING',
'CONTACTED',
'CONVERTED',
'CLOSED'
) DEFAULT 'PENDING',
assigned_to BIGINT,
notes TEXT,
due_date DATE,
FOREIGN KEY (customer_id) REFERENCES customers(id),
FOREIGN KEY (website_lead_id) REFERENCES website_leads(id),



FOREIGN KEY (feedback_id) REFERENCES customer_feedback(id),
FOREIGN KEY (assigned_to) REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
