CREATE TABLE loyalty_transactions (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
customer_id BIGINT NOT NULL,
transaction_type ENUM(
'EARNED',
'REDEEMED',
'ADJUSTED'
) NOT NULL,
points DECIMAL(12,2) NOT NULL,
reference_type ENUM(
'ORDER',
'MANUAL',
'PROMOTION'
) DEFAULT 'ORDER',
reference_id BIGINT,
notes TEXT,
FOREIGN KEY (customer_id) REFERENCES customers(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
