CREATE TABLE asset_maintenance_schedules (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
asset_id BIGINT NOT NULL,
maintenance_type ENUM(
'INSPECTION',
'SERVICE',
'REPAIR',
'CLEANING',
'CALIBRATION'
) NOT NULL,
scheduled_date DATE NOT NULL,
maintenance_status ENUM(
'PENDING',
'IN_PROGRESS',
'COMPLETED',
'OVERDUE',
'CANCELLED'



) DEFAULT 'PENDING',
assigned_to BIGINT,
notes TEXT,
FOREIGN KEY (asset_id) REFERENCES assets(id),
FOREIGN KEY (assigned_to) REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
