CREATE TABLE asset_damage_reports (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
asset_id BIGINT NOT NULL,
reported_by BIGINT,
damage_date DATE NOT NULL,
damage_description TEXT NOT NULL,
damage_status ENUM(
'REPORTED',
'UNDER_REVIEW',
'REPAIR_REQUIRED',
'WRITEOFF_REQUESTED',
'RESOLVED'
) DEFAULT 'REPORTED',
estimated_loss DECIMAL(12,2) DEFAULT 0,
FOREIGN KEY (asset_id) REFERENCES assets(id),
FOREIGN KEY (reported_by) REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
