CREATE TABLE staff_shifts (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
shift_name VARCHAR(255) NOT NULL,
start_time TIME NOT NULL,
end_time TIME NOT NULL,
grace_minutes INT DEFAULT 10,
shift_status ENUM(
'ACTIVE',
'INACTIVE'
) DEFAULT 'ACTIVE',
notes TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
