CREATE TABLE duty_rosters (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
staff_id BIGINT NOT NULL,
shift_id BIGINT NOT NULL,
duty_date DATE NOT NULL,
duty_department ENUM(
'STORE',
'KITCHEN',
'SERVICE',
'DISPATCH',
'BAR',
'HRM',
'FINANCE',
'ADMIN'
) NOT NULL,
roster_status ENUM(
'SCHEDULED',
'COMPLETED',
'MISSED',
'CANCELLED'
) DEFAULT 'SCHEDULED',
notes TEXT,
FOREIGN KEY (staff_id) REFERENCES users(id),
FOREIGN KEY (shift_id) REFERENCES staff_shifts(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
