CREATE TABLE absence_reports (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
staff_id BIGINT NOT NULL,
duty_roster_id BIGINT,
absence_date DATE NOT NULL,
absence_reason TEXT,
absence_status ENUM(
'REPORTED',
'APPROVED',
'REJECTED',
'UNEXPLAINED'
) DEFAULT 'REPORTED',
reported_by BIGINT,
FOREIGN KEY (staff_id) REFERENCES users(id),
FOREIGN KEY (duty_roster_id) REFERENCES duty_rosters(id),
FOREIGN KEY (reported_by) REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
