CREATE TABLE payroll_placeholders (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
staff_id BIGINT NOT NULL,
payroll_month VARCHAR(7) NOT NULL,
base_pay DECIMAL(12,2) DEFAULT 0,
bonus_pay DECIMAL(12,2) DEFAULT 0,
lateness_deduction DECIMAL(12,2) DEFAULT 0,
absence_deduction DECIMAL(12,2) DEFAULT 0,


gross_pay DECIMAL(12,2) DEFAULT 0,
net_pay DECIMAL(12,2) DEFAULT 0,
payroll_status ENUM(
'DRAFT',
'REVIEWED',
'APPROVED',
'PAID'
) DEFAULT 'DRAFT',
notes TEXT,
FOREIGN KEY (staff_id) REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
