CREATE TABLE staff_incidents (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
staff_id BIGINT NOT NULL,
incident_date DATE NOT NULL,
incident_type ENUM(
'CASH_VARIANCE',
'STOCK_VARIANCE',
'ATTENDANCE_VIOLATION',
'PRICING_VIOLATION',
'UNAUTHORIZED_DISCOUNT',
'ORDER_CANCELLATION',
'CUSTOMER_COMPLAINT',
'ASSET_DAMAGE',
'GENERAL_MISCONDUCT'
) NOT NULL,
severity ENUM(
'LOW',
'MEDIUM',
'HIGH',
'CRITICAL'
) DEFAULT 'LOW',
description TEXT NOT NULL,
incident_status ENUM(
'OPEN',
'UNDER_REVIEW',
'RESOLVED',
'CLOSED'
) DEFAULT 'OPEN',
reported_by BIGINT,
FOREIGN KEY (staff_id) REFERENCES users(id),
FOREIGN KEY (reported_by) REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
