CREATE TABLE enforcement_actions (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
staff_id BIGINT NOT NULL,
action_type ENUM(
'VERBAL_WARNING',
'WRITTEN_WARNING',
'DEDUCTION_REVIEW',
'SUSPENSION_REVIEW',
'MANAGER_REVIEW',
'INVESTIGATION',
'TRAINING_REQUIRED'
) NOT NULL,
action_status ENUM(
'PENDING',
'IN_PROGRESS',
'COMPLETED',
'CANCELLED'
) DEFAULT 'PENDING',
reason TEXT NOT NULL,
assigned_to BIGINT,
due_date DATE,
FOREIGN KEY (staff_id) REFERENCES users(id),
FOREIGN KEY (assigned_to) REFERENCES users(id),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
