<?php
declare(strict_types=1);
namespace Controllers;
use Support\Auth;
use Support\Database;
use Support\Request;
use Support\Response;
use Support\AuditLogger;
class EnforcementController
{
public function staffIncidents(): void
{
Auth::requireRole(['SUPER_ADMIN', 'ADMIN', 'MANAGER', 'HR']);
$stmt = Database::connection()->query(
"SELECT
si.*,
staff.full_name AS staff_name,
reporter.full_name AS reported_by_name
FROM staff_incidents si
JOIN users staff ON staff.id = si.staff_id
LEFT JOIN users reporter ON reporter.id = si.reported_by
ORDER BY si.created_at DESC"
);
Response::success(['staff_incidents' => $stmt->fetchAll()]);
}
public function createStaffIncident(): void
{
$user = Auth::requireRole(['SUPER_ADMIN', 'ADMIN', 'MANAGER', 'HR']);
$data = Request::body();
$stmt = Database::connection()->prepare(
'INSERT INTO staff_incidents
(staff_id, incident_date, incident_type, severity, description, reported_by)
VALUES (:staff_id, :incident_date, :incident_type, :severity, :description, :reported_by)'
);
$stmt->execute([
'staff_id' => $data['staff_id'],
'incident_date' => $data['incident_date'],
'incident_type' => $data['incident_type'],
'severity' => $data['severity'] ?? 'LOW',
'description' => $data['description'],
'reported_by' => $user['id'],
]);
AuditLogger::log(
(int) $user['id'],
'ENFORCEMENT',
'CREATE_STAFF_INCIDENT',
(int) $data['staff_id'],
null,
$data
);
Response::success([], 'Staff incident created');
}
public function riskScores(): void
{
Auth::requireRole(['SUPER_ADMIN', 'ADMIN', 'MANAGER', 'HR']);
$stmt = Database::connection()->query(
"SELECT
ers.*,
u.full_name AS staff_name,
u.role
FROM enforcement_risk_scores ers
JOIN users u ON u.id = ers.staff_id
ORDER BY ers.risk_date DESC, ers.total_risk_score DESC"
);
Response::success(['risk_scores' => $stmt->fetchAll()]);
}
public function generateRiskScores(): void
{
$user = Auth::requireRole(['SUPER_ADMIN', 'ADMIN', 'MANAGER', 'HR']);
$db = Database::connection();
$staffStmt = $db->query(


"SELECT id, role FROM users
WHERE role IN ('WAITER', 'CASHIER', 'CHEF', 'STOREKEEPER', 'BARMAN', 'DISPATCHER', 'ACCOUNTANT',
'HR')
AND is_active = 1"
);
$staffMembers = $staffStmt->fetchAll();
$created = 0;
foreach ($staffMembers as $staff) {
$staffId = (int) $staff['id'];
$auditScore = $this->countAuditActions($staffId) * 1;
$approvalScore = $this->countApprovalRequests($staffId) * 3;
$stockVarianceScore = $this->countStockVarianceRelated($staffId) * 5;
$cashVarianceScore = $this->countCashVarianceRelated($staffId) * 5;
$attendanceScore = $this->countAttendanceViolations($staffId) * 4;
$pricingViolationScore = $this->countPricingViolations($staffId) * 5;
$incidentScore = $this->incidentSeverityScore($staffId);
$total = $auditScore
+ $approvalScore
+ $stockVarianceScore
+ $cashVarianceScore
+ $attendanceScore
+ $pricingViolationScore
+ $incidentScore;
$riskLevel = $this->riskLevel($total);
$insert = $db->prepare(
'INSERT INTO enforcement_risk_scores
(staff_id, risk_date, audit_score, approval_score, stock_variance_score,
cash_variance_score, attendance_score, pricing_violation_score,
incident_score, total_risk_score, risk_level, notes)
VALUES
(:staff_id, CURDATE(), :audit_score, :approval_score, :stock_score,
:cash_score, :attendance_score, :pricing_score,
:incident_score, :total_score, :risk_level, :notes)'
);
$insert->execute([
'staff_id' => $staffId,
'audit_score' => $auditScore,
'approval_score' => $approvalScore,
'stock_score' => $stockVarianceScore,
'cash_score' => $cashVarianceScore,
'attendance_score' => $attendanceScore,
'pricing_score' => $pricingViolationScore,
'incident_score' => $incidentScore,
'total_score' => $total,
'risk_level' => $riskLevel,
'notes' => 'Generated by Enforcement Engine',
]);
$created++;
}
AuditLogger::log(
(int) $user['id'],
'ENFORCEMENT',
'GENERATE_RISK_SCORES',
null,
null,
['created' => $created]
);
Response::success(['created' => $created], 'Risk scores generated');
}
public function actions(): void
{
Auth::requireRole(['SUPER_ADMIN', 'ADMIN', 'MANAGER', 'HR']);
$stmt = Database::connection()->query(
"SELECT
ea.*,
staff.full_name AS staff_name,
assignee.full_name AS assigned_to_name
FROM enforcement_actions ea
JOIN users staff ON staff.id = ea.staff_id
LEFT JOIN users assignee ON assignee.id = ea.assigned_to
ORDER BY ea.created_at DESC"
);
Response::success(['enforcement_actions' => $stmt->fetchAll()]);
}


public function createAction(): void
{
$user = Auth::requireRole(['SUPER_ADMIN', 'ADMIN', 'MANAGER', 'HR']);
$data = Request::body();
$stmt = Database::connection()->prepare(
'INSERT INTO enforcement_actions
(staff_id, action_type, action_status, reason, assigned_to, due_date)
VALUES (:staff_id, :action_type, "PENDING", :reason, :assigned_to, :due_date)'
);
$stmt->execute([
'staff_id' => $data['staff_id'],
'action_type' => $data['action_type'],
'reason' => $data['reason'],
'assigned_to' => $data['assigned_to'] ?? $user['id'],
'due_date' => $data['due_date'] ?? null,
]);
AuditLogger::log(
(int) $user['id'],
'ENFORCEMENT',
'CREATE_ENFORCEMENT_ACTION',
(int) $data['staff_id'],
null,
$data
);
Response::success([], 'Enforcement action created');
}
public function dashboard(): void
{
Auth::requireRole(['SUPER_ADMIN', 'ADMIN', 'MANAGER', 'HR']);
$db = Database::connection();
$summary = $db->query(
"SELECT
COUNT(*) AS scored_staff,
SUM(CASE WHEN risk_level = 'LOW' THEN 1 ELSE 0 END) AS low_risk,
SUM(CASE WHEN risk_level = 'MEDIUM' THEN 1 ELSE 0 END) AS medium_risk,
SUM(CASE WHEN risk_level = 'HIGH' THEN 1 ELSE 0 END) AS high_risk,
SUM(CASE WHEN risk_level = 'CRITICAL' THEN 1 ELSE 0 END) AS critical_risk
FROM enforcement_risk_scores
WHERE risk_date = CURDATE()"
)->fetch();
$openIncidents = $db->query(
"SELECT COUNT(*) AS total
FROM staff_incidents
WHERE incident_status IN ('OPEN', 'UNDER_REVIEW')"
)->fetch();
$pendingActions = $db->query(
"SELECT COUNT(*) AS total
FROM enforcement_actions
WHERE action_status IN ('PENDING', 'IN_PROGRESS')"
)->fetch();
$topRisk = $db->query(
"SELECT
ers.*,
u.full_name,
u.role
FROM enforcement_risk_scores ers
JOIN users u ON u.id = ers.staff_id
WHERE ers.risk_date = CURDATE()
ORDER BY ers.total_risk_score DESC
LIMIT 10"
)->fetchAll();
Response::success([
'summary' => $summary,
'open_incidents' => (int) $openIncidents['total'],
'pending_actions' => (int) $pendingActions['total'],
'top_risk_staff' => $topRisk,
]);
}
public function auditFeed(): void
{
Auth::requireRole(['SUPER_ADMIN', 'ADMIN', 'MANAGER', 'HR']);
$stmt = Database::connection()->query(
"SELECT


al.*,
u.full_name AS user_name
FROM audit_logs al
LEFT JOIN users u ON u.id = al.user_id
WHERE al.module_name IN (
'PAYMENTS',
'INVENTORY',
'STOREKEEPING',
'APPROVALS',
'HRM',
'PRICING',
'ASSETS',
'ENFORCEMENT'
)
ORDER BY al.created_at DESC
LIMIT 200"
);
Response::success(['audit_feed' => $stmt->fetchAll()]);
}
private function countAuditActions(int $staffId): int
{
$stmt = Database::connection()->prepare(
'SELECT COUNT(*) AS total
FROM audit_logs
WHERE user_id = :staff_id
AND DATE(created_at) = CURDATE()'
);
$stmt->execute(['staff_id' => $staffId]);
$row = $stmt->fetch();
return (int) $row['total'];
}
private function countApprovalRequests(int $staffId): int
{
$stmt = Database::connection()->prepare(
'SELECT COUNT(*) AS total
FROM approval_requests
WHERE requested_by = :staff_id
AND approval_status = "PENDING"'
);
$stmt->execute(['staff_id' => $staffId]);
$row = $stmt->fetch();
return (int) $row['total'];
}
private function countStockVarianceRelated(int $staffId): int
{
$stmt = Database::connection()->prepare(
"SELECT COUNT(*) AS total
FROM staff_incidents
WHERE staff_id = :staff_id
AND incident_type = 'STOCK_VARIANCE'
AND incident_status IN ('OPEN', 'UNDER_REVIEW')"
);
$stmt->execute(['staff_id' => $staffId]);
$row = $stmt->fetch();
return (int) $row['total'];
}
private function countCashVarianceRelated(int $staffId): int
{
$stmt = Database::connection()->prepare(
"SELECT COUNT(*) AS total
FROM staff_incidents
WHERE staff_id = :staff_id
AND incident_type = 'CASH_VARIANCE'
AND incident_status IN ('OPEN', 'UNDER_REVIEW')"
);
$stmt->execute(['staff_id' => $staffId]);
$row = $stmt->fetch();
return (int) $row['total'];
}
private function countAttendanceViolations(int $staffId): int
{
$stmt = Database::connection()->prepare(
"SELECT COUNT(*) AS total


FROM staff_attendance
WHERE staff_id = :staff_id
AND attendance_date = CURDATE()
AND attendance_status IN ('LATE', 'ABSENT', 'LEFT_EARLY')"
);
$stmt->execute(['staff_id' => $staffId]);
$row = $stmt->fetch();
return (int) $row['total'];
}
private function countPricingViolations(int $staffId): int
{
$stmt = Database::connection()->prepare(
'SELECT COUNT(*) AS total
FROM price_change_audit
WHERE changed_by = :staff_id
AND DATE(created_at) = CURDATE()'
);
$stmt->execute(['staff_id' => $staffId]);
$row = $stmt->fetch();
return (int) $row['total'];
}
private function incidentSeverityScore(int $staffId): int
{
$stmt = Database::connection()->prepare(
"SELECT severity, COUNT(*) AS total
FROM staff_incidents
WHERE staff_id = :staff_id
AND incident_status IN ('OPEN', 'UNDER_REVIEW')
GROUP BY severity"
);
$stmt->execute(['staff_id' => $staffId]);
$rows = $stmt->fetchAll();
$score = 0;
foreach ($rows as $row) {
$weight = match ($row['severity']) {
'LOW' => 2,
'MEDIUM' => 5,
'HIGH' => 10,
'CRITICAL' => 20,
default => 1,
};
$score += $weight * (int) $row['total'];
}
return $score;
}
private function riskLevel(float $score): string
{
if ($score >= 50) {
return 'CRITICAL';
}
if ($score >= 30) {
return 'HIGH';
}
if ($score >= 15) {
return 'MEDIUM';
}
return 'LOW';
}
}
