#!/bin/bash
# Database Error Fix Script
# Applies all fixes from DATABASE_ERRORS_REPORT.md
# Date: August 7, 2026

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
API_DIR="$(dirname "$SCRIPT_DIR")"

echo "🔧 DATABASE ERROR FIX SCRIPT"
echo "========================================"
echo ""
echo "This script will fix the following issues:"
echo "  1. Create missing employee profiles (10 users)"
echo "  2. Revoke expired refresh tokens (8 tokens)"
echo "  3. Fix migration lock provider mismatch"
echo ""
read -p "Do you want to proceed? (yes/no): " CONFIRM

if [ "$CONFIRM" != "yes" ]; then
    echo "❌ Aborted by user"
    exit 0
fi

cd "$API_DIR"

echo ""
echo "=========================================="
echo "📋 Phase 1: Fix Missing Employee Profiles"
echo "=========================================="
echo ""

npx prisma db execute --file scripts/fix_missing_employee_profiles.sql
if [ $? -eq 0 ]; then
    echo "✅ Employee profiles created successfully"
else
    echo "❌ Failed to create employee profiles"
    exit 1
fi

echo ""
echo "=========================================="
echo "🔑 Phase 2: Clean Up Expired Tokens"
echo "=========================================="
echo ""

npx prisma db execute --file scripts/cleanup_expired_tokens.sql
if [ $? -eq 0 ]; then
    echo "✅ Expired tokens revoked successfully"
else
    echo "❌ Failed to revoke expired tokens"
    exit 1
fi

echo ""
echo "=========================================="
echo "⚙️  Phase 3: Fix Migration Lock"
echo "=========================================="
echo ""

cat > prisma/migrations/migration_lock.toml << 'EOF'
# Please do not edit this file manually
# It should be added in your version-control system (e.g., Git)
provider = "postgresql"
EOF

if [ $? -eq 0 ]; then
    echo "✅ Migration lock file updated to PostgreSQL"
    echo ""
    echo "Testing prisma migrate status..."
    npx prisma migrate status || echo "⚠️  Note: No pending migrations"
else
    echo "❌ Failed to update migration lock"
    exit 1
fi

echo ""
echo "=========================================="
echo "🧪 Phase 4: Verification"
echo "=========================================="
echo ""

echo "Running database integrity check..."
node scripts/check_database_integrity.js

if [ $? -eq 0 ]; then
    echo ""
    echo "=========================================="
    echo "✅ ALL FIXES APPLIED SUCCESSFULLY!"
    echo "=========================================="
    echo ""
    echo "Summary:"
    echo "  ✅ Employee profiles created"
    echo "  ✅ Expired tokens revoked"
    echo "  ✅ Migration lock fixed"
    echo "  ✅ Database integrity verified"
    echo ""
    echo "Next steps:"
    echo "  1. Test HR module with staff profiles"
    echo "  2. Set up automated token cleanup cron job"
    echo "  3. Monitor database health regularly"
    echo ""
else
    echo ""
    echo "⚠️  Fixes applied but verification found issues"
    echo "Please check the output above for details"
    echo ""
fi
